@TodoApi_HostAddress = http://localhost:5027

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true,
  "secret":"yeah"
}

###

POST {{TodoApi_HostAddress}}/todoitems/

###

GET {{TodoApi_HostAddress}}/todoitems/

###
